### ISSUE TITLE
Support Arbitrary Depth in adzMapping for TraT Resources

### ISSUE THREAD

**Issue by kchiranjewee63** [tratteria/tratteria#64]
## Current Behavior

The `adzMapping` field in TraT  resources currently only supports single-depth JSON construction for the `adz` field. When attempting to create a TraT with nested adzMapping, the resource fails to be created without providing a status or error message.

## Desired Behavior

The `adzMapping` field should support arbitrary depth, allowing for the creation of nested JSON structures in the `adz` field of the TraT.

## Example

The following TraT resource fails to be created:

```yaml
apiVersion: tratteria.io/v1alpha1
kind: TraT
metadata:
  name: stock-trade-api-trat
  namespace: alpha-stocks-dev
spec:
  path: "/api/order"
  method: "POST"
  purp: stock-trade
  azdMapping:
    stockId:
      required: true
      value: "${body.stockId}"
    action:
      required: true
      value: 
        type:
          required: true
          value: "${body.action.type}"
        name:
          required: true
          value: "${body.action.name}"
    quantity:
      required: true
      value: "${body.quantity}"
  services:
    - name: order
    - name: stocks
      path: "/internal/stocks"
  accessEvaluation:
    subject:
      id: "${subject_token.email}"
    action:
      name: "${body.orderType}"
    resource:
      stockId: "${body.stockId}"
```

## Current Output

When checking the status of TraTs:

```bash
$ kubectl get trats -n alpha-stocks-dev
NAME                      STATUS   AGE   RETRIES
stock-details-api-trat    DONE     22s   0
stock-holdings-api-trat   DONE     22s   0
stock-search-api-trat     DONE     22s   0
stock-trade-api-trat               22s
```

Note that `stock-trade-api-trat` has no STATUS and 0 RETRIES, indicating a silent failure.
